### PR TITLE
blog node-red

### PR DESCRIPTION
**Pull request by vicente87**
In this blog, a brief description of the Node-RED software is made to give way to an explanation of the process of creating subflow and nodes that will be able to interact with a series of services that are in the OSCAR cluster. In addition, a series of examples of workflows in Node-RED are shown, which invoke a series of OSCAR services. These examples are developed based on flow programming where the user enters the data according to the service to be invoked and the result sent by OSCAR is displayed.

### CODE REVIEW

**Review by gmolto — CHANGES_REQUESTED** [review]
Thanks for the work. I updated the PR to rephrase some sections for enhanced readability. Please, take a careful look into the suggestions to get used to the redaction style. Required changes: 
-  Improve the resolution of the Node-Red and OSCAR logs in the header of the blog entry.

**Comment by SergioLangaritaBenitez** [comment]
I would change the installation and security sections (1.1 and 1.2). Instead, I would make a deployment example of Nodered with IM.

**Comment by gmolto** [comment]
I skimmed through the text and it is ready to be deployed. @SergioLangaritaBenitez We can discuss in the deployment through the IM in a further entry. Please double check and merge.

**Comment by gmolto** [comment]
@SergioLangaritaBenitez Please, double check and merge.

**Review by SergioLangaritaBenitez — APPROVED** [review]

**Review by SergioLangaritaBenitez — APPROVED** [review]

**Review by SergioLangaritaBenitez — APPROVED** [review]

**Review by gmolto — APPROVED** [review]

**Pull request merged**
